name: Robert Kilmarx Photography
favicon: null
layout_spectrum: 0.9943914981558919
typography_spectrum: 0.592950607649982
title: Robert Kilmarx Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3e1805'
    - '#737f0a'
    - '#d86227'
    - '#d7e169'
    - '#c31a57'
  brandStrength: 0.966000325512141
  lightness: 0.7775483331643045
  saturation: 0.2675990113057196
  rhythmicContrast: 0.25
purpose: []
